Presentation/Models/ErrorViewModel.cs
namespace SvenMalliaEPSolution.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Presentation/Models/PollViewModel.cs
using Domain.Models;

namespace Presentation.Models
{
    public class PollViewModel
    {
        public Poll Poll { get; set; }
        public string UserEmail { get; set; }
        public bool HasVoted { get; set; }
    }
}

Presentation/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SvenMalliaEPSolution.Models;

namespace SvenMalliaEPSolution.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Presentation/Controllers/PollController.cs
using DataAccess.Repositories;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Presentation.ActionFilters;

namespace Presentation.Controllers
{
    public class PollController : Controller
    {
        public IActionResult Index([FromServices] PollFileRepository pollFileRepository)
        {
            var pollList = pollFileRepository.GetPolls().OrderByDescending(x => x.DateCreated).Select(x => new Poll
            {
                Id = x.Id,
                DateCreated = x.DateCreated,
                Title = x.Title,
            });
            return View(pollList);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([FromServices] PollFileRepository pollFileRepository, Poll poll)
        {
            if (ModelState.IsValid)
            {
                pollFileRepository.CreatePoll(poll);
                return RedirectToAction("Index");
            }
            return View(poll);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Vote(int id, [FromServices] PollFileRepository pollFileRepository)
        {
            var poll = pollFileRepository.GetPolls().Where(x => x.Id == id).Select(x => new Poll
            {
                Id = x.Id,
                Title = x.Title,
                DateCreated = x.DateCreated,
                Option1Text = x.Option1Text,
                Option2Text = x.Option2Text,
                Option3Text = x.Option3Text,
            }).First();
            if (poll == null)
                return RedirectToAction("Index");
            return View(poll);
        }

        [HttpPost]
        [ServiceFilter(typeof(VoteActionFilter))]
        public IActionResult Vote([FromServices] PollFileRepository pollRepository, Poll poll)
        {
            pollRepository.Vote(poll);
            return RedirectToAction("VoteResult", new { id = poll.Id});
        }

        [HttpGet]
        public IActionResult VoteResult(int id, [FromServices] PollFileRepository pollRepository)
        {
            var poll = pollRepository.GetPolls().Select(x => new Poll
            {
                Id = x.Id,
                Title = x.Title,
                Option1Text = x.Option1Text,
                Option2Text = x.Option2Text,
                Option3Text = x.Option3Text,
                Option1VotesCount = x.Option1VotesCount,
                Option2VotesCount = x.Option2VotesCount,
                Option3VotesCount = x.Option3VotesCount

            }).First(x => x.Id == id);
            if (poll == null)
                return RedirectToAction("Index");
            return View(poll);
        }
    }
}

Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Presentation/Views/Poll/Create.cshtml
@model Domain.Models.Poll

<form method="post" action="/Poll/Create" class="container mt-4">
	<div class="mb-3">
		<label for="title" class="form-label">Poll Title:</label>
		<input type="text" name="Poll.Title" class="form-control" required />
	</div>
	<div class="mb-3">
		<label for="title" class="form-label">Option 1 Text:</label>
		<input type="text" name="Poll.Option1Text" class="form-control" required />
	</div>

	<div class="mb-3">
		<label for="title" class="form-label">Option 2 Text:</label>
		<input type="text" name="Poll.Option2Text" class="form-control" required />
	</div>

	<div class="mb-3">
		<label for="title" class="form-label">Option 3 Text:</label>
		<input type="text" name="Poll.Option3Text" class="form-control" required />
	</div>
	<button type="submit" class="btn btn-primary">Add Poll</button>
</form>

Presentation/Views/Poll/Index.cshtml
@model IEnumerable<Domain.Models.Poll>
@{
	ViewData["Title"] = "Index";
}
<div class="row">
    @foreach (var poll in Model)
    {
        <div class="col-md-4 mb-4">
                    <h5 class="card-title">@poll.Title</h5>
                    <h5 class="card-title">Created at @poll.DateCreated</h5>
                    <a href="/Poll/Vote?id=@poll.Id" class="btn btn-primary">Vote</a>
                    <a href="/Poll/VoteResult?id=@poll.Id" class="btn btn-primary">View Results</a>
        </div>
    }
    <a href="/Poll/Create" class="btn btn-primary">Create Poll</a>
</div>

Presentation/Views/Poll/Vote.cshtml
@model Domain.Models.Poll

<h2>@Model.Title</h2>
<h2>@Model.Id</h2>
<form method="post" action="/Poll/Vote" class="container mt-4" enctype="multipart/form-data">
	<div class="mb3">
		<input type="number" value="@Model.Id" readonly name="Poll.Id" hidden/>
		<select name="Poll.Option1VotesCount" class="form-select">
			<option value="1">@Model.Option1Text</option>
			<option value="2">@Model.Option2Text</option>
			<option value="3">@Model.Option3Text</option>
		</select>
	</div>
	<button type="submit" class="btn btn-primary">Vote</button>

</form>

Presentation/Views/Poll/VoteResult.cshtml
@model Domain.Models.Poll
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<h1>Vote Results</h1>
<canvas id="myChart" style="width:100%;max-width:300px"></canvas>
<script>
    var xValues = ["@Model.Option1Text", "@Model.Option2Text", "@Model.Option3Text"];
    var yValues = [@Model.Option1VotesCount, @Model.Option2VotesCount, @Model.Option3VotesCount];
    var barColors = ["red", "green","blue"];

    new Chart("myChart", {
      type: "doughnut",
      data: {
        labels: xValues,
        datasets: [{
          backgroundColor: barColors,
          data: yValues
        }]
      },
      options: {
        title: {
          display: true,
          text: "@Model.Title"
        }
      }
    });
</script>

Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SvenMalliaEPSolution</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SvenMalliaEPSolution.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SvenMalliaEPSolution</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Poll" asp-action="Index">Polls</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - SvenMalliaEPSolution - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>